# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CacheBuster < Formula
  desc "Developer cache manager with configurable size limits"
  homepage "https://github.com/Automaat/cache-buster"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Automaat/cache-buster/releases/download/v0.7.0/cache-buster_0.7.0_darwin_amd64.tar.gz"
      sha256 "8982b6d5ee4e4232333e375c5bdd5bfd8abaaccf69e953865fb7a8c6bd58fb01"

      define_method(:install) do
        bin.install "cache-buster"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Automaat/cache-buster/releases/download/v0.7.0/cache-buster_0.7.0_darwin_arm64.tar.gz"
      sha256 "ea88a6cfa4e028cee27771d0f03f5761214e222f54d13bf84b5361c766dc7c13"

      define_method(:install) do
        bin.install "cache-buster"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Automaat/cache-buster/releases/download/v0.7.0/cache-buster_0.7.0_linux_amd64.tar.gz"
      sha256 "4f0ac8b769e3236f45060d71a75117659920dc4b89cc6f30f62697c8c5f47750"
      define_method(:install) do
        bin.install "cache-buster"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Automaat/cache-buster/releases/download/v0.7.0/cache-buster_0.7.0_linux_arm64.tar.gz"
      sha256 "a1d3e704b651e047f9f49c02860d8cb0ac768369c419458918c97b01b25626c3"
      define_method(:install) do
        bin.install "cache-buster"
      end
    end
  end

  test do
    system "#{bin}/cache-buster --version"
  end
end
