# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CacheBuster < Formula
  desc "Developer cache manager with configurable size limits"
  homepage "https://github.com/Automaat/cache-buster"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Automaat/cache-buster/releases/download/v0.6.0/cache-buster_0.6.0_darwin_amd64.tar.gz"
      sha256 "e0223c96af757cec0f1ce1132a77bb040747519a183cb12667658771afdb416d"

      def install
        bin.install "cache-buster"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Automaat/cache-buster/releases/download/v0.6.0/cache-buster_0.6.0_darwin_arm64.tar.gz"
      sha256 "183290e9b6d8dbb64c8c9c6642c8cb04bfacb1a4c8a642e786215fd45e3cdabf"

      def install
        bin.install "cache-buster"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Automaat/cache-buster/releases/download/v0.6.0/cache-buster_0.6.0_linux_amd64.tar.gz"
      sha256 "c13b36af7b72112e84dc8b8eaadcf9b76305789da58bfbc4efee7460f80363aa"
      def install
        bin.install "cache-buster"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Automaat/cache-buster/releases/download/v0.6.0/cache-buster_0.6.0_linux_arm64.tar.gz"
      sha256 "17464f62b9d88adc9a81a1abe4dc15b1c2f49e4743c0cffbc71aa4bd2755edab"
      def install
        bin.install "cache-buster"
      end
    end
  end

  test do
    system "#{bin}/cache-buster --version"
  end
end
