# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CacheBuster < Formula
  desc "Developer cache manager with configurable size limits"
  homepage "https://github.com/Automaat/cache-buster"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Automaat/cache-buster/releases/download/v0.8.0/cache-buster_0.8.0_darwin_amd64.tar.gz"
      sha256 "05d6e0e47ac06317942f897d974904a113d31e168bf3338420f7af5005e00644"

      define_method(:install) do
        bin.install "cache-buster"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Automaat/cache-buster/releases/download/v0.8.0/cache-buster_0.8.0_darwin_arm64.tar.gz"
      sha256 "76c34a8fe1a551875c8a04fbd8a7496966705bbe8af0d30e4a99eddcebd998e4"

      define_method(:install) do
        bin.install "cache-buster"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Automaat/cache-buster/releases/download/v0.8.0/cache-buster_0.8.0_linux_amd64.tar.gz"
      sha256 "1e444f1f88dbd531876d2cd43dd5aa77563926bd35fc107fbc5503a75057a150"
      define_method(:install) do
        bin.install "cache-buster"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Automaat/cache-buster/releases/download/v0.8.0/cache-buster_0.8.0_linux_arm64.tar.gz"
      sha256 "7be94a362b927fbab30de117184fdf8ee83eb441b404dc5b4ce13ac89638fa04"
      define_method(:install) do
        bin.install "cache-buster"
      end
    end
  end

  test do
    system "#{bin}/cache-buster --version"
  end
end
