# typed: false
# frozen_string_literal: true

# Generated by the zsh-clean-history release workflow. DO NOT EDIT.
class ZshCleanHistory < Formula
  desc "Smart zsh history cleanup: removes typos and failed commands"
  homepage "https://github.com/Automaat/zsh-clean-history"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Automaat/zsh-clean-history/releases/download/v0.2.1/zsh-clean-history-0.2.1-aarch64-apple-darwin.tar.gz"
      sha256 "46d57548514f16fee17eab5631e2cf808c1bcda8d9b67642c252fdbc84f8de28"
    end
    if Hardware::CPU.intel?
      url "https://github.com/Automaat/zsh-clean-history/releases/download/v0.2.1/zsh-clean-history-0.2.1-x86_64-apple-darwin.tar.gz"
      sha256 "38788dd50a754f9ff1c626b809a10e1e2864f7ca50c914281ae24c8637e3861e"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Automaat/zsh-clean-history/releases/download/v0.2.1/zsh-clean-history-0.2.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "f8cda43e5de5e7c45b298db5a338af86bb6d42dcc68289b03c00e8dc4c3363be"
    end
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Automaat/zsh-clean-history/releases/download/v0.2.1/zsh-clean-history-0.2.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "09cb2208823809f06bffc12e8024d7a4bfbd33bc4b1fddd131ee9ebd77fc81c0"
    end
  end

  def install
    bin.install "zsh-clean-history"
    man1.install "man/zsh-clean-history.1"
    zsh_completion.install "completions/_zsh-clean-history"
    bash_completion.install "completions/zsh-clean-history.bash"
    fish_completion.install "completions/zsh-clean-history.fish"
    pkgshare.install "zsh-clean-history.plugin.zsh"
  end

  def caveats
    <<~EOS
      To record exit codes, source the plugin from your ~/.zshrc:
        source #{opt_pkgshare}/zsh-clean-history.plugin.zsh
    EOS
  end

  test do
    system bin/"zsh-clean-history", "--version"
  end
end
